### ISSUE TITLE
App-Publisher hard-coded architecture errors

### ISSUE THREAD

**Issue by m-lenz** [eclipse/kuksa.apps#20]
The apps can be built for `amd` or `arm32vX` and images are automatically tagged as such.
e.g. arm32v6/kuksa-traccar:0.1.0 (arch/name:version)

[![docker.png](https://i.postimg.cc/FztBy7TL/docker.png)](https://postimg.cc/MMD5xK26)

However, the publisher looks for those parameters in the `yaml`-config file. The [Traccar-config](https://github.com/eclipse/kuksa.apps/blob/master/kuksa-app-publisher/kuksa-traccar.yaml) yields the wrong architecture, which results in an error.

**Comment by rai20** [comment]
The .yaml file is only an example file. But this can be modified to push arm32vX or amd images by modifying it accordingly. You need to look at the .yaml files as config files which do exactly that.
But I see in the example .yaml file armhf is used, probably I can change that to arm32v6.
Moreover the ip addresses have been set to some random num´ber because we are not allowed to publish the internal ip-addresses.

**Comment by m-lenz** [comment]
Good to know. Maybe then we should delete various tokens and login-information from the repos e.g.

https://github.com/eclipse/kuksa.apps/tree/master/invehicle-apps/kuksa-cloud-mechanic/docker
https://github.com/eclipse/kuksa.apps/tree/master/invehicle-apps/kuksa-cloud-dashboard/docker

which expose Hono- and HawkBit-logins. Even if the `IP` is kept private, we should not rely on it, since it violates the Kerckhoffs-principle.

How will the configs be handled in the future? Will the logins disappear from the config or do we just hope no-one will open it and extract the data?
